#!/usr/bin/env node
"use strict";

// Clears the per-user / transactional Firestore collections so the real Google
// Sheet -> Firestore migration imports into a clean database. Configuration
// collections are NEVER touched. Dry-run by default; pass --commit with the
// exact --confirmText to actually delete.
//
//   Dry run (counts only):
//     node tools/clear_staging_data.js --project mydietitian --serviceAccount "<path>"
//   Real delete:
//     node tools/clear_staging_data.js --project mydietitian --serviceAccount "<path>" \
//       --commit --confirmText CLEAR_STAGING_MYDIETITIAN

const admin = require("firebase-admin");

const CONFIRM_TEXT = "CLEAR_STAGING_MYDIETITIAN";

// Per-user / transactional data — safe to clear before a fresh migration
// (everything here is re-imported from the Sheet or regenerated by the bot).
const CLEARABLE = [
  "users", "profiles", "subscriptions", "lineLinks", "authLinks",
  "mealLogs", "weightLogs", "exerciseLogs", "biaReports",
  "paymentReviews", "subscriptionEvents", "subscriptionRequests",
  "profileEvents", "profileAuthEvents", "aiRuns",
  "lineEvents", "lineEventDedup", "adminAuditLogs",
  "adminChatSessions", "adminChatMessages", "leftoverIntents",
  "migrationRuns", "redeemCodes"
];

// Configuration — must survive the wipe.
const KEEP = ["appConfig", "aiAgents", "subscriptionPlans"];

const args = parseArgs(process.argv.slice(2));
const projectId = args.project || "mydietitian";
const commit = Boolean(args.commit);

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (!arg.startsWith("--")) continue;
    const key = arg.slice(2);
    const next = argv[i + 1];
    if (next === undefined || next.startsWith("--")) {
      out[key] = true;
    } else {
      out[key] = next;
      i += 1;
    }
  }
  return out;
}

function initFirebase() {
  if (args.serviceAccount) {
    const credentialJson = require(require("node:path").resolve(args.serviceAccount));
    if (!credentialJson.project_id) {
      process.env.GOOGLE_APPLICATION_CREDENTIALS = args.serviceAccount;
      admin.initializeApp({ credential: admin.credential.applicationDefault(), projectId });
      return;
    }
    admin.initializeApp({ credential: admin.credential.cert(credentialJson), projectId });
    return;
  }
  admin.initializeApp({ projectId });
}

async function countCollection(db, name) {
  try {
    const snap = await db.collection(name).count().get();
    return snap.data().count;
  } catch {
    return null;
  }
}

async function deleteCollection(db, name) {
  let deleted = 0;
  for (;;) {
    const snap = await db.collection(name).limit(400).get();
    if (snap.empty) break;
    let batch = db.batch();
    snap.docs.forEach((doc) => batch.delete(doc.ref));
    await batch.commit();
    deleted += snap.size;
    process.stdout.write(`  ${name}: ${deleted}\r`);
  }
  return deleted;
}

async function main() {
  if (commit && args.confirmText !== CONFIRM_TEXT) {
    throw new Error(`Refusing to delete. Pass --confirmText ${CONFIRM_TEXT} together with --commit.`);
  }

  initFirebase();
  const db = admin.firestore();

  console.log(commit ? "DELETING per-user/transactional collections." : "DRY RUN: counts only (pass --commit to delete).");
  console.log("KEEP (never touched):", KEEP.join(", "));
  console.log("");

  const result = {};
  let total = 0;
  for (const name of CLEARABLE) {
    if (commit) {
      const deleted = await deleteCollection(db, name);
      result[name] = deleted;
      total += deleted;
      console.log(`  ${name}: deleted ${deleted}      `);
    } else {
      const count = await countCollection(db, name);
      result[name] = count;
      total += count || 0;
      console.log(`  ${name}: ${count ?? "n/a"}`);
    }
  }

  console.log("");
  console.log(JSON.stringify({ project: projectId, mode: commit ? "deleted" : "dry-run", totalDocuments: total, byCollection: result }, null, 2));
}

main().then(() => process.exit(0)).catch((error) => {
  console.error(error.message || String(error));
  process.exit(1);
});
