#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

const args = parseArgs(process.argv.slice(2));
const projectId = args.project || "mydietitian";
const serviceAccount = args.serviceAccount || "C:\\Users\\champ\\AppData\\Roaming\\firebase\\znak_iiz_gmail.com_application_default_credentials.json";
const templatePath = path.resolve(args.template || "docs/MANUAL_UAT_EVIDENCE_TEMPLATE.md");
const outPath = path.resolve(args.out || "docs/MANUAL_UAT_EVIDENCE.md");
const force = Boolean(args.force);
const refreshExisting = Boolean(args.refreshExisting || args["refresh-existing"]);
const tester = clean(args.tester);
const lineChannel = clean(args.lineChannel || args["line-channel"]);
const testLineUserId = clean(args.testLineUserId || args["test-line-user-id"]);
const currentGasWebhookUrl = clean(args.currentGasWebhookUrl || args["current-gas-webhook-url"]);
const operator = clean(args.operator);
const useLineSecretManager = Boolean(args.useLineSecretManager || args["use-line-secret-manager"]);
const lineSecretName = clean(args.lineSecretName || args["line-secret-name"] || "LINE_CHANNEL_SECRET");

main();

function main() {
  const outExists = fs.existsSync(outPath);
  if (outExists && !force && !refreshExisting) {
    throw new Error(`${outPath} already exists. Pass --force to overwrite or --refresh-existing to preserve manual rows.`);
  }

  const template = fs.readFileSync(templatePath, "utf8");
  const base = refreshExisting && outExists ? fs.readFileSync(outPath, "utf8") : template;
  const preCutoverCommand = [
    "npm", "run", "report:pre-cutover", "--",
    "--project", projectId,
    "--serviceAccount", serviceAccount,
    "--smoke-write"
  ];
  if (useLineSecretManager) preCutoverCommand.push("--useLineSecretManager", "--lineSecretName", lineSecretName);
  const preCutover = runJson("pre-cutover report", preCutoverCommand);
  const aiReadiness = runJson("AI fallback readiness", [
    "node", "tools/check_ai_fallback_readiness.js",
    "--project", projectId
  ]);
  const aiRuntime = runJson("AI agent runtime config", [
    "node", "tools/check_ai_agent_runtime_config.js",
    "--project", projectId,
    "--serviceAccount", serviceAccount,
    "--require-anthropic-fallback"
  ]);
  const lineUat = runJson("LINE text dry-run", ["npm", "run", "line:uat-report", "--", "--json"]);
  const signedWebhookCommand = [
    "npm", "run", "test:line-webhook", "--",
    "--scenario", "text",
    "--user", "U_STAGING_CONTRACT_TEST",
    "--webhook-dry-run"
  ];
  if (useLineSecretManager) signedWebhookCommand.push("--useLineSecretManager", "--lineSecretName", lineSecretName);
  const signedWebhook = runJson("Signed LINE webhook contract", signedWebhookCommand);
  const invalidTokenUser = testLineUserId || existingTwoColumnValue(base, "Test LINE user ID") || "U_STAGING_INVALID_TOKEN_TEST";
  const invalidToken = runJson("LIFF invalid token negative test", [
    "npm", "run", "uat:liff-invalid-token", "--",
    "--user", invalidTokenUser
  ]);
  const dashboard = runJson("Dashboard contract", ["npm", "run", "dashboard:contract"]);
  const migration = runJson("Migration dry-run", ["npm", "run", "migrate:sheets:dry-run", "--", "--sampleLimit", "5"]);
  const commit = currentGitCommit();
  const fingerprint = migration.json?.migrationReadiness?.sourceFingerprint?.value || "";
  const generatedAt = new Date().toLocaleString("sv-SE", { timeZone: "Asia/Bangkok" }).replace(" ", "T");
  const auditSummary = preCutover.json?.automatedChecks?.find((check) => check.name === "pre-migration audit")?.summary || {};
  const auditNoSkipped = Number(auditSummary.failed ?? 0) === 0 && Number(auditSummary.skipped ?? 0) === 0;
  const lineUatOk = lineUat.ok && Number(lineUat.json?.summary?.textScenarioFailed ?? 0) === 0 && Number(lineUat.json?.summary?.textScenarioPassed ?? 0) >= 13;
  const migrationOk = Boolean(migration.json?.migrationReadiness?.dataQuality?.okToPreviewImport);
  const setupOk = preCutover.ok && auditNoSkipped && aiReadiness.ok && aiRuntime.ok && lineUatOk && signedWebhook.ok && invalidToken.ok && dashboard.ok && migrationOk && Boolean(commit) && Boolean(fingerprint);

  let output = base;
  output = replaceTwoColumnRow(output, "Date/time (Asia/Bangkok)", generatedAt);
  output = replaceTwoColumnRow(output, "Tester", tester || existingTwoColumnValue(base, "Tester"));
  output = replaceTwoColumnRow(output, "Staging LINE OA/channel", lineChannel || existingTwoColumnValue(base, "Staging LINE OA/channel"));
  output = replaceTwoColumnRow(output, "Test LINE user ID", testLineUserId || existingTwoColumnValue(base, "Test LINE user ID"));
  output = replaceTwoColumnRow(output, "Notes", refreshExisting
    ? "Refreshed automated evidence by `tools/prepare_manual_uat_evidence.js --refresh-existing`; manual rows preserved."
    : "Generated by `tools/prepare_manual_uat_evidence.js`; complete real LINE/LIFF rows manually.");

  output = replaceThreeColumnRow(output, "Pre-cutover report", "`ok=true`", preCutover.ok ? "`ok=true`" : "`fail`");
  output = replaceThreeColumnRow(output, "Pre-migration audit", "all checks pass with `--smoke-write --useLineSecretManager`", summarizePreMigrationAudit(preCutover.json));
  output = replaceThreeColumnRow(output, "AI fallback readiness", "both Gemini and Anthropic secrets ready", aiReadiness.ok ? "`ok=true`" : "`fail`");
  output = replaceThreeColumnRow(output, "AI agent runtime config", "`gemini-3.5-flash` primary and `claude-sonnet-4-6` fallback", aiRuntime.ok ? "`ok=true`" : "`fail`");
  output = replaceThreeColumnRow(output, "LINE text dry-run", "`13/13` text scenarios pass", summarizeLineUat(lineUat.json));
  output = replaceThreeColumnRow(output, "Signed LINE webhook contract", "`mode=line-webhook-contract-dry-run`", signedWebhook.ok ? "`mode=line-webhook-contract-dry-run`" : "pending real `LINE_CHANNEL_SECRET` input");
  output = replaceThreeColumnRow(output, "Dashboard contract", "`ok=true`", dashboard.ok ? "`ok=true`" : "`fail`");
  output = replaceThreeColumnRow(output, "Migration dry-run", "`okToPreviewImport=true`", migration.json?.migrationReadiness?.dataQuality?.okToPreviewImport ? "`okToPreviewImport=true`" : "`fail`");
  output = replaceResultEvidenceRow(
    output,
    "Invalid token rejected",
    invalidToken.ok ? "pass" : "fail",
    invalidToken.json?.evidenceText || "Expected 401 profile-auth-failed from controlled invalid token test."
  );

  output = replaceTwoColumnRow(output, "Current GAS webhook URL", currentGasWebhookUrl || existingTwoColumnValue(base, "Current GAS webhook URL"));
  output = replaceTwoColumnRow(output, "LINE channel", lineChannel || existingTwoColumnValue(base, "LINE channel"));
  output = replaceTwoColumnRow(output, "Operator", operator || existingTwoColumnValue(base, "Operator"));
  output = replaceTwoColumnRow(output, "Latest commit SHA", `\`${commit}\``);
  output = replaceTwoColumnRow(output, "Latest Google Sheet source fingerprint", `\`${fingerprint}\``);
  output = replaceFourColumnRow(output, "Automated pre-cutover report", "pass", preCutover.ok ? "pass" : "fail", existingFourColumnValue(base, "Automated pre-cutover report", 3));

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, output, "utf8");
  console.log(JSON.stringify({
    ok: setupOk,
    out: outPath,
    mode: refreshExisting ? "refresh-existing" : "create-from-template",
    commit,
    sourceFingerprint: fingerprint,
    setupFailures: [
      ...(preCutover.ok ? [] : [`pre-cutover report failed: ${preCutover.error || "unknown"}`]),
      ...(auditNoSkipped ? [] : [`pre-migration audit must have 0 failed and 0 skipped; summary=${JSON.stringify(auditSummary)}`]),
      ...(aiReadiness.ok ? [] : [`AI fallback readiness failed: ${aiReadiness.error || "unknown"}`]),
      ...(aiRuntime.ok ? [] : [`AI runtime config failed: ${aiRuntime.error || "unknown"}`]),
      ...(lineUatOk ? [] : [`LINE text dry-run did not pass all required scenarios: ${lineUat.error || JSON.stringify(lineUat.json?.summary || {})}`]),
      ...(signedWebhook.ok ? [] : [`signed LINE webhook contract failed: ${signedWebhook.error || "unknown"}`]),
      ...(invalidToken.ok ? [] : [`LIFF invalid token negative test failed: ${invalidToken.error || "unknown"}`]),
      ...(dashboard.ok ? [] : [`dashboard contract failed: ${dashboard.error || "unknown"}`]),
      ...(migrationOk ? [] : ["migration dry-run data quality was not okToPreviewImport=true"]),
      ...(commit ? [] : ["git commit SHA was not detected"]),
      ...(fingerprint ? [] : ["migration dry-run source fingerprint was not detected"])
    ],
    manualFieldsRemaining: [
      ...(tester ? [] : ["Tester"]),
      ...(lineChannel ? [] : ["Staging LINE OA/channel", "LINE channel"]),
      ...(testLineUserId ? [] : ["Test LINE user ID"]),
      "Real LINE media UAT rows",
      "Real LIFF auth UAT rows except the automated invalid-token negative test",
      "Security Preflight secret rotation row",
      ...(currentGasWebhookUrl ? [] : ["Rollback Current GAS webhook URL"]),
      ...(operator ? [] : ["Operator"]),
      "Owner sign-off rows"
    ]
  }, null, 2));

  if (!setupOk) process.exit(1);
}

function replaceTwoColumnRow(text, label, value) {
  return replaceTableRow(text, label, () => [label, value]);
}

function replaceThreeColumnRow(text, label, expected, actual) {
  return replaceTableRow(text, label, () => [label, expected, actual]);
}

function replaceFourColumnRow(text, label, required, actual, signoff) {
  return replaceTableRow(text, label, () => [label, required, actual, signoff || ""]);
}

function replaceResultEvidenceRow(text, label, result, evidence) {
  return replaceTableRow(text, label, (cells) => [
    cells[0],
    cells[1] || "",
    cells[2] || "",
    result,
    evidence
  ]);
}

function replaceTableRow(text, label, buildCells) {
  return text.split(/\r?\n/).map((line) => {
    const cells = parseTableLine(line);
    if (!cells || normalizeCell(cells[0]) !== normalizeCell(label)) return line;
    return formatTableLine(buildCells(cells));
  }).join("\n");
}

function existingTwoColumnValue(text, label) {
  return existingTableValue(text, label, 1);
}

function existingFourColumnValue(text, label, columnIndex) {
  return existingTableValue(text, label, columnIndex);
}

function existingTableValue(text, label, columnIndex) {
  for (const line of text.split(/\r?\n/)) {
    const cells = parseTableLine(line);
    if (cells && normalizeCell(cells[0]) === normalizeCell(label)) return cells[columnIndex] || "";
  }
  return "";
}

function parseTableLine(line) {
  const trimmed = line.trim();
  if (!trimmed.startsWith("|") || !trimmed.endsWith("|") || trimmed.includes("---")) return null;
  return trimmed.slice(1, -1).split("|").map((cell) => cell.trim());
}

function formatTableLine(cells) {
  return `| ${cells.map((cell) => String(cell ?? "").trim()).join(" | ")} |`;
}

function normalizeCell(value) {
  return String(value || "").replace(/`/g, "").trim().toLowerCase().replace(/\s+/g, " ");
}

function runJson(name, command, env = {}) {
  const result = spawnCommand(command, env);
  return parseCommandJson(name, result);
}

function parseCommandJson(name, result) {
  const output = `${result.stdout || ""}\n${result.stderr || ""}`;
  const json = parseLastJsonObject(output);
  const error = result.error ? String(result.error) : null;
  return {
    name,
    ok: result.status === 0 && Boolean(json) && Boolean(json.ok ?? true),
    status: result.status,
    json,
    error: result.status === 0 ? null : (error || summarize(output))
  };
}

function spawnCommand(command, env = {}) {
  const mergedEnv = { ...process.env, ...env };
  if (process.platform === "win32" && needsCmdShim(command[0])) {
    const commandLine = command.map(quoteCmdArg).join(" ");
    return spawnSync("cmd.exe", ["/d", "/s", "/c", commandLine], {
      cwd: process.cwd(),
      encoding: "utf8",
      shell: false,
      env: mergedEnv,
      maxBuffer: 40 * 1024 * 1024
    });
  }
  return spawnSync(resolveExecutable(command[0]), command.slice(1), {
    cwd: process.cwd(),
    encoding: "utf8",
    shell: false,
    env: mergedEnv,
    maxBuffer: 40 * 1024 * 1024
  });
}

function summarizeLineUat(json) {
  const passed = Number(json?.summary?.textScenarioPassed ?? 0);
  const failed = Number(json?.summary?.textScenarioFailed ?? 0);
  return passed >= 13 && failed === 0 ? `\`${passed}/13 pass\`` : `\`${passed}/13 pass, ${failed} failed\``;
}

function summarizePreMigrationAudit(json) {
  const audit = json?.automatedChecks?.find((check) => check.name === "pre-migration audit");
  const summary = audit?.summary || {};
  const passed = Number(summary.passed ?? 0);
  const failed = Number(summary.failed ?? 0);
  const skipped = Number(summary.skipped ?? 0);
  if (audit?.ok && failed === 0 && skipped === 0) return `\`${passed} passed / 0 failed / 0 skipped\``;
  if (audit?.ok) return `\`${passed} passed / ${failed} failed / ${skipped} skipped\``;
  return "`fail`";
}

function currentGitCommit() {
  const result = spawnSync(resolveExecutable("git"), ["rev-parse", "HEAD"], {
    cwd: process.cwd(),
    encoding: "utf8"
  });
  return result.status === 0 ? result.stdout.trim() : "";
}

function resolveExecutable(command) {
  if (process.platform !== "win32") return command;
  if (/\.(cmd|exe|bat)$/i.test(command)) return command;
  if (["npm", "npx", "firebase", "gcloud"].includes(command)) return `${command}.cmd`;
  return command;
}

function needsCmdShim(command) {
  return ["npm", "npx", "firebase", "gcloud"].includes(command) || /\.(cmd|bat)$/i.test(command);
}

function quoteCmdArg(value) {
  const text = String(value || "");
  if (!text) return "\"\"";
  if (!/[\s"&|<>^]/.test(text)) return text;
  return `"${text.replace(/"/g, "\"\"")}"`;
}

function parseLastJsonObject(text) {
  const end = text.lastIndexOf("}");
  if (end < 0) return null;
  const starts = [];
  const pattern = /(?:^|\n)\s*\{/g;
  let match;
  while ((match = pattern.exec(text))) {
    starts.push(match.index + (text[match.index] === "\n" ? 1 : 0));
  }
  for (const start of starts) {
    try {
      return JSON.parse(text.slice(start, end + 1));
    } catch {
      // Keep scanning likely top-level JSON starts.
    }
  }
  return null;
}

function summarize(text) {
  return String(text || "").split(/\r?\n/).filter(Boolean).slice(-5).join(" ");
}

function clean(value) {
  return String(value || "").trim();
}

function parseArgs(argv) {
  const out = {};
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (!arg.startsWith("--")) continue;
    const key = arg.slice(2);
    const value = argv[index + 1];
    if (!value || value.startsWith("--")) {
      out[key] = true;
    } else {
      out[key] = value;
      index += 1;
    }
  }
  return out;
}
