#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

const args = parseArgs(process.argv.slice(2));
const projectId = args.project || "mydietitian";
const serviceAccount = args.serviceAccount || "C:\\Users\\champ\\AppData\\Roaming\\firebase\\znak_iiz_gmail.com_application_default_credentials.json";
const templatePath = path.resolve(args.template || "docs/MANUAL_UAT_EVIDENCE_TEMPLATE.md");
const outPath = path.resolve(args.out || "docs/MANUAL_UAT_EVIDENCE.md");
const force = Boolean(args.force);
const tester = clean(args.tester);
const lineChannel = clean(args.lineChannel || args["line-channel"]);
const testLineUserId = clean(args.testLineUserId || args["test-line-user-id"]);
const currentGasWebhookUrl = clean(args.currentGasWebhookUrl || args["current-gas-webhook-url"]);
const operator = clean(args.operator);
const useLineSecretManager = Boolean(args.useLineSecretManager || args["use-line-secret-manager"]);
const lineSecretName = clean(args.lineSecretName || args["line-secret-name"] || "LINE_CHANNEL_SECRET");

main();

function main() {
  if (fs.existsSync(outPath) && !force) {
    throw new Error(`${outPath} already exists. Pass --force to overwrite the local working copy.`);
  }

  const template = fs.readFileSync(templatePath, "utf8");
  const preCutover = runJson("pre-cutover report", [
    "npm", "run", "report:pre-cutover", "--",
    "--project", projectId,
    "--serviceAccount", serviceAccount,
    "--smoke-write"
  ]);
  const aiReadiness = runJson("AI fallback readiness", [
    "node", "tools/check_ai_fallback_readiness.js",
    "--project", projectId
  ]);
  const aiRuntime = runJson("AI agent runtime config", [
    "node", "tools/check_ai_agent_runtime_config.js",
    "--project", projectId,
    "--serviceAccount", serviceAccount,
    "--require-anthropic-fallback"
  ]);
  const lineUat = runJson("LINE text dry-run", ["npm", "run", "line:uat-report", "--", "--json"]);
  const lineSecret = process.env.LINE_CHANNEL_SECRET || (useLineSecretManager ? accessSecret(lineSecretName) : "");
  const signedWebhook = lineSecret
    ? runJson("Signed LINE webhook contract", [
      "npm", "run", "test:line-webhook", "--",
      "--scenario", "text",
      "--user", "U_STAGING_CONTRACT_TEST",
      "--webhook-dry-run"
    ], { LINE_CHANNEL_SECRET: lineSecret })
    : { ok: false, skipped: true };
  const dashboard = runJson("Dashboard contract", ["npm", "run", "dashboard:contract"]);
  const migration = runJson("Migration dry-run", ["npm", "run", "migrate:sheets:dry-run", "--", "--sampleLimit", "5"]);
  const commit = currentGitCommit();
  const fingerprint = migration.json?.migrationReadiness?.sourceFingerprint?.value || "";
  const generatedAt = new Date().toLocaleString("sv-SE", { timeZone: "Asia/Bangkok" }).replace(" ", "T");
  const setupOk = preCutover.ok && aiReadiness.ok && aiRuntime.ok && dashboard.ok && Boolean(commit) && Boolean(fingerprint);

  let output = template
    .replace("| Date/time (Asia/Bangkok) |  |", `| Date/time (Asia/Bangkok) | ${generatedAt} |`)
    .replace("| Tester |  |", `| Tester | ${tester} |`)
    .replace("| Staging LINE OA/channel |  |", `| Staging LINE OA/channel | ${lineChannel} |`)
    .replace("| Test LINE user ID |  |", `| Test LINE user ID | ${testLineUserId} |`)
    .replace("| Notes |  |", "| Notes | Generated by `tools/prepare_manual_uat_evidence.js`; complete real LINE/LIFF rows manually. |")
    .replace("| Pre-cutover report | `ok=true` |  |", `| Pre-cutover report | \`ok=true\` | ${preCutover.ok ? "`ok=true`" : "`fail`"} |`)
    .replace("| Pre-migration audit | all checks pass with `--smoke-write` |  |", `| Pre-migration audit | all checks pass with \`--smoke-write\` | ${preCutover.json?.automatedChecks?.find((check) => check.name === "pre-migration audit")?.ok ? "`pass`" : "`fail`"} |`)
    .replace("| AI fallback readiness | both Gemini and Anthropic secrets ready |  |", `| AI fallback readiness | both Gemini and Anthropic secrets ready | ${aiReadiness.ok ? "`ok=true`" : "`fail`"} |`)
    .replace("| AI agent runtime config | `gemini-3.5-flash` primary and `claude-sonnet-4-6` fallback |  |", `| AI agent runtime config | \`gemini-3.5-flash\` primary and \`claude-sonnet-4-6\` fallback | ${aiRuntime.ok ? "`ok=true`" : "`fail`"} |`)
    .replace("| LINE text dry-run | `13/13` text scenarios pass |  |", `| LINE text dry-run | \`13/13\` text scenarios pass | ${summarizeLineUat(lineUat.json)} |`)
    .replace("| Signed LINE webhook contract | `mode=line-webhook-contract-dry-run` |  |", `| Signed LINE webhook contract | \`mode=line-webhook-contract-dry-run\` | ${signedWebhook.ok ? "`mode=line-webhook-contract-dry-run`" : "pending real `LINE_CHANNEL_SECRET` input"} |`)
    .replace("| Dashboard contract | `ok=true` |  |", `| Dashboard contract | \`ok=true\` | ${dashboard.ok ? "`ok=true`" : "`fail`"} |`)
    .replace("| Migration dry-run | `okToPreviewImport=true` |  |", `| Migration dry-run | \`okToPreviewImport=true\` | ${migration.json?.migrationReadiness?.dataQuality?.okToPreviewImport ? "`okToPreviewImport=true`" : "`fail`"} |`)
    .replace("| Current GAS webhook URL |  |", `| Current GAS webhook URL | ${currentGasWebhookUrl} |`)
    .replace("| LINE channel |  |", `| LINE channel | ${lineChannel} |`)
    .replace("| Operator |  |", `| Operator | ${operator} |`)
    .replace("| Latest commit SHA |  |", `| Latest commit SHA | \`${commit}\` |`)
    .replace("| Latest Google Sheet source fingerprint |  |", `| Latest Google Sheet source fingerprint | \`${fingerprint}\` |`)
    .replace("| Automated pre-cutover report | pass |  |  |", `| Automated pre-cutover report | pass | ${preCutover.ok ? "pass" : "fail"} |  |`);

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, output, "utf8");
  console.log(JSON.stringify({
    ok: setupOk,
    out: outPath,
    commit,
    sourceFingerprint: fingerprint,
    setupFailures: [
      ...(preCutover.ok ? [] : [`pre-cutover report failed: ${preCutover.error || "unknown"}`]),
      ...(aiReadiness.ok ? [] : [`AI fallback readiness failed: ${aiReadiness.error || "unknown"}`]),
      ...(aiRuntime.ok ? [] : [`AI runtime config failed: ${aiRuntime.error || "unknown"}`]),
      ...(dashboard.ok ? [] : [`dashboard contract failed: ${dashboard.error || "unknown"}`]),
      ...(commit ? [] : ["git commit SHA was not detected"]),
      ...(fingerprint ? [] : ["migration dry-run source fingerprint was not detected"])
    ],
    manualFieldsRemaining: [
      ...(tester ? [] : ["Tester"]),
      ...(lineChannel ? [] : ["Staging LINE OA/channel", "LINE channel"]),
      ...(testLineUserId ? [] : ["Test LINE user ID"]),
      "Real LINE media UAT rows",
      "Real LIFF auth UAT rows",
      ...(currentGasWebhookUrl ? [] : ["Rollback Current GAS webhook URL"]),
      ...(operator ? [] : ["Operator"]),
      "Owner sign-off rows"
    ]
  }, null, 2));
}

function runJson(name, command, env = {}) {
  const result = spawnCommand(command, env);
  return parseCommandJson(name, result);
}

function parseCommandJson(name, result) {
  const output = `${result.stdout || ""}\n${result.stderr || ""}`;
  const json = parseLastJsonObject(output);
  const error = result.error ? String(result.error) : null;
  return {
    name,
    ok: result.status === 0 && Boolean(json) && Boolean(json.ok ?? true),
    status: result.status,
    json,
    error: result.status === 0 ? null : (error || summarize(output))
  };
}

function spawnCommand(command, env = {}) {
  const mergedEnv = { ...process.env, ...env };
  if (process.platform === "win32" && needsCmdShim(command[0])) {
    const commandLine = command.map(quoteCmdArg).join(" ");
    return spawnSync("cmd.exe", ["/d", "/s", "/c", commandLine], {
      cwd: process.cwd(),
      encoding: "utf8",
      shell: false,
      env: mergedEnv,
      maxBuffer: 40 * 1024 * 1024
    });
  }
  return spawnSync(resolveExecutable(command[0]), command.slice(1), {
    cwd: process.cwd(),
    encoding: "utf8",
    shell: false,
    env: mergedEnv,
    maxBuffer: 40 * 1024 * 1024
  });
}

function accessSecret(secretName) {
  const result = spawnCommand([
    "gcloud", "secrets", "versions", "access", "latest",
    "--secret", secretName,
    "--project", projectId
  ]);
  if (result.status !== 0) return "";
  return String(result.stdout || "").trim();
}

function summarizeLineUat(json) {
  const passed = Number(json?.summary?.textScenarioPassed ?? 0);
  const failed = Number(json?.summary?.textScenarioFailed ?? 0);
  return passed >= 13 && failed === 0 ? `\`${passed}/13 pass\`` : `\`${passed}/13 pass, ${failed} failed\``;
}

function currentGitCommit() {
  const result = spawnSync(resolveExecutable("git"), ["rev-parse", "HEAD"], {
    cwd: process.cwd(),
    encoding: "utf8"
  });
  return result.status === 0 ? result.stdout.trim() : "";
}

function resolveExecutable(command) {
  if (process.platform !== "win32") return command;
  if (/\.(cmd|exe|bat)$/i.test(command)) return command;
  if (["npm", "npx", "firebase", "gcloud"].includes(command)) return `${command}.cmd`;
  return command;
}

function needsCmdShim(command) {
  return ["npm", "npx", "firebase", "gcloud"].includes(command) || /\.(cmd|bat)$/i.test(command);
}

function quoteCmdArg(value) {
  const text = String(value || "");
  if (!text) return "\"\"";
  if (!/[\s"&|<>^]/.test(text)) return text;
  return `"${text.replace(/"/g, "\"\"")}"`;
}

function parseLastJsonObject(text) {
  const end = text.lastIndexOf("}");
  if (end < 0) return null;
  const starts = [];
  const pattern = /(?:^|\n)\s*\{/g;
  let match;
  while ((match = pattern.exec(text))) {
    starts.push(match.index + (text[match.index] === "\n" ? 1 : 0));
  }
  for (const start of starts) {
    try {
      return JSON.parse(text.slice(start, end + 1));
    } catch {
      // Keep scanning likely top-level JSON starts.
    }
  }
  return null;
}

function summarize(text) {
  return String(text || "").split(/\r?\n/).filter(Boolean).slice(-5).join(" ");
}

function clean(value) {
  return String(value || "").trim();
}

function parseArgs(argv) {
  const out = {};
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (!arg.startsWith("--")) continue;
    const key = arg.slice(2);
    const value = argv[index + 1];
    if (!value || value.startsWith("--")) {
      out[key] = true;
    } else {
      out[key] = value;
      index += 1;
    }
  }
  return out;
}
